const currencies = [
  { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ', countries: 'United Arab Emirates' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', countries: 'Afghanistan' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', countries: 'Albania' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', countries: 'Armenia' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', countries: 'Curaçao, Sint Maarten' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', countries: 'Angola' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', countries: 'Argentina' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', countries: 'Australia, Kiribati, Nauru, Tuvalu' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', countries: 'Aruba' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', countries: 'Azerbaijan' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', countries: 'Bosnia and Herzegovina' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', countries: 'Barbados' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', countries: 'Bangladesh' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', countries: 'Bulgaria' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', countries: 'Bahrain' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', countries: 'Burundi' },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', countries: 'Bermuda' },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', countries: 'Brunei' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', countries: 'Bolivia' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', countries: 'Brazil' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', countries: 'Bahamas' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', countries: 'Bhutan' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', countries: 'Botswana' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', countries: 'Belarus' },
  { code: 'BZD', name: 'Belize Dollar', symbol: '$', countries: 'Belize' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', countries: 'Canada' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', countries: 'Democratic Republic of the Congo' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', countries: 'Switzerland, Liechtenstein' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', countries: 'Chile' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', countries: 'China' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', countries: 'Colombia' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', countries: 'Costa Rica' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', countries: 'Cuba' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', countries: 'Cape Verde' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', countries: 'Czech Republic' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', countries: 'Djibouti' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', countries: 'Denmark, Faroe Islands, Greenland' },
  { code: 'DOP', name: 'Dominican Peso', symbol: '$', countries: 'Dominican Republic' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', countries: 'Algeria' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£', countries: 'Egypt' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', countries: 'Eritrea' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', countries: 'Ethiopia' },
  { code: 'EUR', name: 'Euro', symbol: '€', countries: 'Eurozone (19 countries)' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', countries: 'Fiji' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', countries: 'Falkland Islands' },
  { code: 'FOK', name: 'Faroese Króna', symbol: 'kr', countries: 'Faroe Islands' },
  { code: 'GBP', name: 'British Pound Sterling', symbol: '£', countries: 'United Kingdom' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', countries: 'Georgia' },
  { code: 'GGP', name: 'Guernsey Pound', symbol: '£', countries: 'Guernsey' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', countries: 'Ghana' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', countries: 'Gibraltar' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', countries: 'Gambia' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', countries: 'Guinea' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', countries: 'Guatemala' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', countries: 'Guyana' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', countries: 'Hong Kong' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', countries: 'Honduras' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', countries: 'Croatia' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', countries: 'Haiti' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', countries: 'Hungary' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', countries: 'Indonesia' },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', countries: 'Israel' },
  { code: 'IMP', name: 'Isle of Man Pound', symbol: '£', countries: 'Isle of Man' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', countries: 'India' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', countries: 'Iraq' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', countries: 'Iran' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', countries: 'Iceland' },
  { code: 'JEP', name: 'Jersey Pound', symbol: '£', countries: 'Jersey' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: '$', countries: 'Jamaica' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', countries: 'Jordan' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', countries: 'Japan' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', countries: 'Kenya' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', countries: 'Kyrgyzstan' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', countries: 'Cambodia' },
  { code: 'KID', name: 'Kiribati Dollar', symbol: '$', countries: 'Kiribati' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', countries: 'Comoros' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', countries: 'South Korea' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', countries: 'Kuwait' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', countries: 'Cayman Islands' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', countries: 'Kazakhstan' },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', countries: 'Laos' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', countries: 'Lebanon' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', countries: 'Sri Lanka' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', countries: 'Liberia' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', countries: 'Lesotho' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', countries: 'Libya' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', countries: 'Morocco' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', countries: 'Moldova' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', countries: 'Madagascar' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', countries: 'North Macedonia' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', countries: 'Myanmar' },
  { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', countries: 'Mongolia' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', countries: 'Macau' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', countries: 'Mauritania' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', countries: 'Mauritius' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'ރ.', countries: 'Maldives' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', countries: 'Malawi' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', countries: 'Mexico' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', countries: 'Malaysia' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', countries: 'Mozambique' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', countries: 'Namibia' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', countries: 'Nigeria' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', countries: 'Nicaragua' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', countries: 'Norway' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', countries: 'Nepal' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', countries: 'New Zealand, Cook Islands, Niue, Pitcairn Islands' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', countries: 'Oman' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', countries: 'Panama' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', countries: 'Peru' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', countries: 'Papua New Guinea' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', countries: 'Philippines' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', countries: 'Pakistan' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', countries: 'Poland' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', countries: 'Paraguay' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', countries: 'Qatar' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', countries: 'Romania' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', countries: 'Serbia' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', countries: 'Russia' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', countries: 'Rwanda' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', countries: 'Saudi Arabia' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', countries: 'Solomon Islands' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', countries: 'Seychelles' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: '£', countries: 'Sudan' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', countries: 'Sweden' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', countries: 'Singapore' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', countries: 'Saint Helena' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', countries: 'Sierra Leone' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', countries: 'Somalia' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', countries: 'Suriname' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', countries: 'South Sudan' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', countries: 'São Tomé and Príncipe' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', countries: 'Syria' },
  { code: 'SZL', name: 'Eswatini Lilangeni', symbol: 'L', countries: 'Eswatini' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', countries: 'Thailand' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', countries: 'Tajikistan' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', countries: 'Turkmenistan' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', countries: 'Tunisia' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', countries: 'Tonga' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', countries: 'Turkey' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: '$', countries: 'Trinidad and Tobago' },
  { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$', countries: 'Tuvalu' },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', countries: 'Taiwan' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', countries: 'Tanzania' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', countries: 'Ukraine' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', countries: 'Uganda' },
  { code: 'USD', name: 'US Dollar', symbol: '$', countries: 'United States' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$', countries: 'Uruguay' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: "so'm", countries: 'Uzbekistan' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.', countries: 'Venezuela' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', countries: 'Vietnam' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', countries: 'Vanuatu' },
  { code: 'WST', name: 'Samoan Tālā', symbol: 'T', countries: 'Samoa' },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', countries: 'Cameroon, Chad, Congo, Gabon, etc.' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', countries: 'Antigua, Grenada, St. Lucia, etc.' },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', countries: 'Benin, Ivory Coast, Senegal, etc.' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', countries: 'French Polynesia, New Caledonia' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', countries: 'Yemen' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', countries: 'South Africa' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', countries: 'Zambia' },
  { code: 'ZWL', name: 'Zimbabwean Gold', symbol: 'ZiG', countries: 'Zimbabwe' },
];

export function getCurrencyByCode(code) {
  return currencies.find(c => c.code === code) || null;
}

export default currencies;
