export const TOPBAR_THEMES = {
  purple: {
    id: 'purple',
    name: 'Neon Purple',
    preview: 'linear-gradient(135deg, #7C3AED 0%, #4F46E5 100%)',
    bg: 'linear-gradient(to right, #7C3AED, #4F46E5)',
    textColor: 'text-white',
    subTextColor: 'text-indigo-200',
    iconColor: 'text-white/80 hover:text-white hover:bg-white/15',
    pillBg: 'bg-white/10 border-white/15 text-white',
    salesIconColor: 'text-emerald-400',
    isDark: true,
  },
  slate: {
    id: 'slate',
    name: 'Graphite Grey',
    preview: 'linear-gradient(135deg, #4B5563 0%, #1F2937 100%)',
    bg: 'linear-gradient(to right, #374151, #1F2937)',
    textColor: 'text-white',
    subTextColor: 'text-gray-300',
    iconColor: 'text-gray-200 hover:text-white hover:bg-white/10',
    pillBg: 'bg-gray-700/80 border-gray-600/80 text-white',
    salesIconColor: 'text-emerald-400',
    isDark: true,
  },
  white: {
    id: 'white',
    name: 'Clean White',
    preview: 'linear-gradient(to right, #FFFFFF, #F1F5F9)',
    bg: '#FFFFFF',
    textColor: 'text-gray-900',
    subTextColor: 'text-gray-500',
    iconColor: 'text-gray-600 hover:text-gray-900 hover:bg-gray-100',
    pillBg: 'bg-gray-100 border-gray-200 text-gray-800',
    salesIconColor: 'text-emerald-600',
    isDark: false,
    borderBottom: 'border-b border-gray-200',
  },
  navy: {
    id: 'navy',
    name: 'Royal Navy',
    preview: 'linear-gradient(135deg, #1E1B4B 0%, #1D4ED8 100%)',
    bg: 'linear-gradient(to right, #1E1B4B, #1D4ED8)',
    textColor: 'text-white',
    subTextColor: 'text-blue-200',
    iconColor: 'text-white/80 hover:text-white hover:bg-white/15',
    pillBg: 'bg-white/10 border-white/15 text-white',
    salesIconColor: 'text-blue-300',
    isDark: true,
  },
  emerald: {
    id: 'emerald',
    name: 'Dark Emerald',
    preview: 'linear-gradient(135deg, #064E3B 0%, #059669 100%)',
    bg: 'linear-gradient(to right, #064E3B, #047857)',
    textColor: 'text-white',
    subTextColor: 'text-emerald-200',
    iconColor: 'text-white/80 hover:text-white hover:bg-white/15',
    pillBg: 'bg-white/10 border-white/15 text-white',
    salesIconColor: 'text-emerald-300',
    isDark: true,
  },
  rose: {
    id: 'rose',
    name: 'Ruby Rose',
    preview: 'linear-gradient(135deg, #881337 0%, #E11D48 100%)',
    bg: 'linear-gradient(to right, #881337, #E11D48)',
    textColor: 'text-white',
    subTextColor: 'text-rose-200',
    iconColor: 'text-white/80 hover:text-white hover:bg-white/15',
    pillBg: 'bg-white/10 border-white/15 text-white',
    salesIconColor: 'text-amber-300',
    isDark: true,
  },
  cyan: {
    id: 'cyan',
    name: 'Ocean Cyan',
    preview: 'linear-gradient(135deg, #0891B2 0%, #0284C7 100%)',
    bg: 'linear-gradient(to right, #0891B2, #0284C7)',
    textColor: 'text-white',
    subTextColor: 'text-cyan-100',
    iconColor: 'text-white/80 hover:text-white hover:bg-white/15',
    pillBg: 'bg-white/10 border-white/15 text-white',
    salesIconColor: 'text-cyan-200',
    isDark: true,
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Flame',
    preview: 'linear-gradient(135deg, #C2410C 0%, #EA580C 100%)',
    bg: 'linear-gradient(to right, #C2410C, #EA580C)',
    textColor: 'text-white',
    subTextColor: 'text-orange-200',
    iconColor: 'text-white/80 hover:text-white hover:bg-white/15',
    pillBg: 'bg-white/10 border-white/15 text-white',
    salesIconColor: 'text-amber-300',
    isDark: true,
  },
};

export const DEFAULT_TOPBAR_THEME = 'purple';
